### PR TITLE
[IMP] pass builds with warnings as success to gitlab

### PR DESCRIPTION
**Pull request by hbrunn**
let's show builds with warnings as success but add a comment that there's a warning

### CODE REVIEW

**Comment by moylop260** [comment]
Should be this one a github behavior too?

Is not this change hidding warnings, since that the people don’t open the CI to check the final result?
currently, travis has warnings for this reason.

But lets to hear other opinions

@pedrobaeza @gurneyalex @rvalyi

**Comment by pedrobaeza** [comment]
I prefer to have any kind of highlighting. Runbot warnings are important (it's not the same as pylint ones).

**Comment by hbrunn** [comment]
of course warnings are important, and as soon as we can show them in gitlab somehow, let's please do that. This is a temporary proposal until the API allows something like #164

**Comment by pedrobaeza** [comment]
OK, as you think it's the best. We are not using runbot anymore with our doodba-qa (https://github.com/Tecnativa/doodba-qa) + Gitlab CI solution.

**Comment by hbrunn** [comment]
I think I'll add this as an option. We'll want to treat warnings as errors often, but there are projects where we're happy to have at least no failures for the time being. And as the project matures, you can turn this on again.

**Comment by ap-wtioit** [comment]
I support this pull request (we already do similar stuff on our runbot), especially the solution with the context enables the warning to be  visible in gitlab as well (we don't have that yet)

**Comment by moylop260** [comment]
+1 for me as an option.

**Comment by hbrunn** [comment]
now as an option

**Review by moylop260 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
