### PR TITLE
[11.0][REM] rem all references to weblate

### PR DESCRIPTION
**Pull request by umiphos**
In this PR we are purging weblate, because runbot is not used for the weblate integration in 11.0 version. 
related to #162

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]
LGTM
👍 

Could you bump version of the module, please?

**Review by hbrunn — CHANGES_REQUESTED** [review]
you need to remove the files you delete from the manifest too to fix https://travis-ci.org/OCA/runbot-addons/jobs/397449834#L1099

**Comment by umiphos** [comment]
@hbrunn shame on me, it's now fixed, thanks

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You have to change the module version number and include a migration script that removes the cron (if exists).

**Comment by hbrunn** [comment]
come on pedro. this is not customer stuff, this is our own tools. i think we can expect users here to fix stuff on their own

**Review by hbrunn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
OK, it's not so difficult, but I don't insist

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
