### PR TITLE
[REF] runbot_travis2docker: Set CI environment variables

### PR DESCRIPTION
**Pull request by moylop260**
Require https://github.com/OCA/runbot-addons/pull/92 to see a green CI result

### CODE REVIEW

**Comment by moylop260** [comment]
@lasley @alan196 @pedrobaeza 
Your feedback is welcome

**Comment by moylop260** [comment]
ping

**Comment by lasley** [comment]
Code looks good, not sure how to functionally test this one though.

**Comment by oscarolar** [comment]
👍

**Comment by moylop260** [comment]
Setting environment variables used from MQT
- https://github.com/OCA/maintainer-quality-tools/blob/14aa6f67/travis/travis_run_tests#L51
- https://github.com/OCA/maintainer-quality-tools/blob/14aa6f67/travis/test_server.py#L273-L274

Inspired by https://docs.travis-ci.com/user/environment-variables

**Comment by joaoalf** [comment]
👍 lgtm

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
