### PR TITLE
[FIX] runbot_travis2docker: Compatibility with new version of travis2docker and odoo-extra/runbot:master

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by moylop260** [comment]
This pr fix the current red of 9.0 branch
Now is green for travis

**Comment by lasley** [comment]
Been using this for a few weeks now, works great 👍

**Comment by oscarolar** [comment]
loving t2d 👍

**Comment by alan196** [comment]
I have been using for some time... works perfect :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
