### PR TITLE
[REF] .travis.yml: Fix stdout error

### PR DESCRIPTION
**Pull request by moylop260**
Random message when run 'docker pull IMAGE' like
 - [Errno 11] write could not complete without blocking

Seems as a travis issue:
 - https://github.com/travis-ci/travis-ci/issues/8982#issuecomment-354357640
 - https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959

Currently stable branch has travis red:
 - https://travis-ci.org/OCA/runbot-addons/builds/407457537

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I have found this error in some builds, but isn't a better solution? Should we put this workaround in all the repositories?

**Review by hbrunn — APPROVED** [review]

**Comment by hbrunn** [comment]
I'm not aware of a better fix, and would propose to apply it only where it hurts

**Comment by hbrunn** [comment]
@moylop260 doesn't seem to have helped :-( https://travis-ci.org/OCA/runbot-addons/jobs/428502161#L1090

**Comment by moylop260** [comment]
Ok Thank you
The strange of this is that is not posible reproduce it from a PR.
It just is reproduced it from a stable branch.
What about create a new issue for travis-ci?
-- 
Moisés López Calderón
Mobile: (+521) 477-752-22-30
Twitter: @moylop260
hangout: moylop260@vauxoo.com
http://www.vauxoo.com - Odoo Gold Partner
Twitter: @vauxoo

**Pull request merged**
