### PR TITLE
Runbot custom

### PR DESCRIPTION
**Pull request by bwrsandman**
## Runbot with custom build instructions.

This is useful for custom installation and deployment scripts such as buildout.

Add option in repo form view for custom builds. When checked:
- Modules to test becomes required attribute.
- Custom build directory can be specified. This is where the repo will be cloned in the build directory.
- Custom server path is required to be specified. This is tells runbot which executable script to run.
- Custom server flags can be specified to add to execution. E.g. --workers=0
- Pre-build commands can be run such as additional fetch scripts or buildout.

### CODE REVIEW

**Comment by nhomar** [comment]
We are testing it internally.
It looks really good.

Just one comment if you are agreed:

The name *_custom is to generic it sounds as an extention that make a lot of thing, shouldn't be better if you name runbot_buildout/runbot_custom_enviroment/runbot_multienviroment or something like that.

Thanks a lot dude ;-)

**Comment by bwrsandman** [comment]
@nhomar Honestly, I was thinking of calling it "runboboo"
- runbot_buildout -> too specific to buildout, works perfectly fine for other usages
- runbot_custom_enviroment -> not bad, but kind of long for a name
- runbot_multienviroment -> I don't really understand this one

**Comment by nhomar** [comment]
2014-07-25 20:00 GMT-04:30 Sandy notifications@github.com:

> @nhomar https://github.com/nhomar Honestly, I was thinking of calling
> it "runboboo"

It is a cool name for the App which will install all the features we are
building over runbot as extra ones ;-)

> - runbot_buildout -> too specific to buildout, works perfectly fine
>   for other usages
> 
> Well As you are using buildout I think it can fit. but ok, discarted
> - runbot_custom_enviroment -> not bad, but kind of long for a name
> 
> what about runbot_custom_env?  or simple runbot_enviroment
> - runbot_multienviroment -> I don't really understand this one
> 
> I don't know just continuing with the enviroment stuff ;-)

## 

---

Saludos Cordiales

Nhomar G. Hernandez M.
+58-414-4110269
Skype: nhomar00
Web-Blog: http://geronimo.com.ve
Servicios IT: http://vauxoo.com
Linux-Counter: 467724
Correos:
nhomar@openerp.com.ve
nhomar@vauxoo.com
twitter @nhomar

**Comment by max3903** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

@bwrsandman do you want to change the name before this gets merged?

**Comment by bwrsandman** [comment]
@gurneyalex any suggestions on a new name?

**Comment by lepistone** [comment]
:wave: @gurneyalex

**Comment by yvaucher** [comment]
@bwrsandman 

odoo Runbot -> odoor

/me run

**Comment by bwrsandman** [comment]
@yvaucher :laughing:

**Comment by max3903** [comment]
@bwrsandman runbot_build_instructions

**Comment by foutoucour** [comment]
:+1: 
sexy names like odoor are fun but informative names are better for the SEO

**Comment by max3903** [comment]
:+1:

**Comment by gurneyalex** [comment]
sorry I missed the call here... Thanks for merging :-)

**Pull request merged**
