### PR TITLE
[ADD][11.0] runbot_gitlab

### PR DESCRIPTION
**Pull request by hbrunn**
this is #119 tentatively ported to 11, not yet functional and no tests yet

### CODE REVIEW

**Comment by moylop260** [comment]
Hello @hbrunn

Could you check the following migration work?

https://github.com/Vauxoo/runbot-addons/tree/11.0/runbot_gitlab_minimal

I added support for webhook of gitlab and other fixes for 11.0

(Testing in my runbot is working fine...)

**Comment by hbrunn** [comment]
oh no! why did nobody tell me when I asked about this in https://github.com/OCA/runbot-addons/pull/119#issuecomment-373143618? Anyways, what's done is done.

I just started working on this for a couple of hours, and didn't make any real live tests, so as your version already works in production as I understand, please, PR it here. Then we'll just rename it to runbot_gitlab and hopefully can merge immediately as I propose in https://github.com/OCA/runbot-addons/pull/148#pullrequestreview-109679899 (which I will do with the travis2docker PR as soon as somebody like you screams: Let's do it like that)

**Comment by moylop260** [comment]
FYI https://github.com/OCA/runbot-addons/pull/151

**Comment by hbrunn** [comment]
superseded by #151

**Pull request closed without merging**
