### PR TITLE
[DEL] runbot_subject_skip: Not installable

### PR DESCRIPTION
**Pull request by moylop260**
Because this behavior is now supported from runbot officially

From https://github.com/odoo/runbot/pull/13

### CODE REVIEW

**Comment by moylop260** [comment]
Question:
 - What is the best way to deprecate it?
   - Remove it
   - Uninstallable False

**Review by elicoidal — APPROVED** [review]
LGTM (but why not simply remove the module?)

**Comment by pedrobaeza** [comment]
But AFAIK, we are using a runbot fork, isn't it? Is our fork updated?

**Comment by moylop260** [comment]
I didn't get the fork:
 - https://github.com/oca/runbot is not exists.

Are you talking about https://runbot.odoo-community.org/runbot?

We are not have migrated to 11.0 version yet.
That runbot is using odoo 9.0 yet and this change just affects 11.0.

**Comment by pedrobaeza** [comment]
Ah, OK

**Review by pedrobaeza — APPROVED** [review]

**Comment by moylop260** [comment]
The question here is
Should we delete the module?

**Comment by pedrobaeza** [comment]
Yes, better to remove it in this branch.

**Pull request merged**
